version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "50051:50051"
    volumes:
      - ./server:/app
    command: ["python", "server.py"]

  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    command: ["python", "client.py"]